<?php 
$themename = "PictureThis";
$shortname = "t";

/* Get Pages into a drop-down list */
$pages_list = get_pages();
$getpagnav = array();
foreach($pages_list as $apage) {
	$getpagnav[$apage->ID] = $apage->post_title;
}

$options = array (
 
array( "name" => $themename." Options",
	"type" => "title"),
 

array( "name" => "General",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Blog Title or Logo",
	"desc" => "Choose if you want to use the blog title or a custom logo",
	"desc2" => "Display Logo",
	"desc3" => "Display Blog Title",
	"value" => "",
	"value2" => "1",
	"id" => "site_name",
	"type" => "radio"),
	
array( "name" => "Logo URL",
	"desc" => "If you selected 'Display Blog Title' above, enter the URL for your logo. If you don't enter it, the default theme logo will be used",
	"id" => "custom_logo",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Logo Width (in pixels)",
	"desc" => "Enter the width of your logo for appropriate page padding/logo resizing.",
	"id" => "logo_width",
	"type" => "text",
	"std" => "152"),
	
array( "name" => "404 Error Message",
	"desc" => "Enter the message that you want to be displayed when a file is missing. It can be HTML",
	"id" => "404_error",
	"type" => "textarea",
	"std" => ""),
	
array( "name" => "Google Analytics Code",
	"desc" => "Enter your google analytics code.",
	"id" => "analytics",
	"type" => "textarea",
	"std" => ""),
	
	array( "type" => "close"),
array( "name" => "Homepage",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Homepage Image Only or Blog w/ Image",
	"desc" => "Select whether you want to display the homepage with the navigation and background image only, or with the blog as well.",
	"desc2" => "Image Only",
	"desc3" => "Blog Page",
	"value" => "",
	"value2" => "1",
	"id" => "homepage_blog",
	"type" => "radio"),
	
array( "name" => "Default Background Image",
	"desc" => "Enter the URL to the background image that you want pages to use by default if no custom background images are set for them. (Any pages/posts you create without setting background image URL(s), this image will be used by default, including on the homepage)",
	"id" => "default_bg_image",
	"type" => "text",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Blog",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Excerpt/Full Blog Post",
	"desc" => "Select whether you would like to display the excerpt or the full blog post on the blog page.",
	"desc2" => "Show Excerpt",
	"desc3" => "Show Full Blog Post",
	"value" => "",
	"value2" => "1",
	"id" => "show_excerpt",
	"type" => "radio"),
	
array( "name" => "Excerpt Length",
	"desc" => "Enter the number of characters that you want the excerpt to display (default is 55)",
	"id" => "excerpt_length",
	"type" => "text",
	"std" => "55"),
	
array(	"name" => "Show/Hide Read More Button",
	"desc" => "Select whether you would like to show or hide the 'Read More' button (only if 'Show Excerpt' is selected above)",
	"desc2" => "Show Read More Button",
	"desc3" => "Hide Read More Button",
	"value" => "",
	"value2" => "1",
	"id" => "show_readmore",
	"type" => "radio"),
	
array( "name" => "Read More Button Text",
	"desc" => "This is the text that will be displayed on the 'Read More' button.",
	"id" => "read_more",
	"type" => "text",
	"std" => "Read More"),
	
array(	"name" => "Category Page Blog Style",
	"desc" => "Choose the blog style you would like to use for blog categories",
	"desc2" => "Fullwidth",
	"desc3" => "Left Thumbnail",
	"value" => "",
	"value2" => "1",
	"id" => "cat_blog_style",
	"type" => "radio"),
	
array(	"name" => "Tag Page Blog Style",
	"desc" => "Choose the blog style you would like to use for blog post tags",
	"desc2" => "Fullwidth",
	"desc3" => "Left Thumbnail",
	"value" => "",
	"value2" => "1",
	"id" => "tag_blog_style",
	"type" => "radio"),
	
array( "type" => "close"),
array( "name" => "Homepage Slider Options",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Slides To Show",
	"desc" => "Enter the number of slides that you want the homepage to cycle through",
	"id" => "homepage_slide_count",
	"type" => "text",
	"std" => "10"),

array(	"name" => "Slideshow On/Off",
	"desc" => "Select if you want the homepage to display the slideshow in the background or use the default background image",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "slideshow_onoff",
	"type" => "radio"),
	
array(	"name" => "Start Slide",
	"desc" => "Start slide or random. (Random will either show the slide when a user visits the page, or will just show the default image with no slideshow)",
	"desc2" => "Start",
	"desc3" => "Random",
	"value" => "",
	"value2" => "1",
	"id" => "start_slide",
	"type" => "radio"),
	
array(	"name" => "Show Images Randomly",
	"desc" => "Select if you want the homepage slideshow to randomly display images or to display them in order.",
	"desc2" => "Yes",
	"desc3" => "No",
	"value" => "",
	"value2" => "1",
	"id" => "random_images",
	"type" => "radio"),
	
array(	"name" => "Pause Slideshow on Mouse Hover",
	"desc" => "Select if you want the homepage slideshow to pause if the user is hovering the background image",
	"desc2" => "Yes",
	"desc3" => "No",
	"value" => "",
	"value2" => "1",
	"id" => "pause_slideshow",
	"type" => "radio"),
	
array(	"name" => "Slideshow Transition effect",
	"desc" => "Select the transition effect you would like the slideshow to use.",
	"id" => "transition_effect",
	"options" => array('Fade', 'Slide Top', 'Slide Left', 'Slide Right', 'Carousel Right', 'Carousel Left'),
	"type" => "select",
	"std" => ""),

array( "name" => "Transition Time",
	"desc" => "Enter the time in milliseconds you want the transition to take (1000 = 1 second)",
	"id" => "transition_time",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Slide Interval",
	"desc" => "Enter the time in milliseconds you want each image/slide to take (1000 = 1 second)",
	"id" => "slide_interval",
	"type" => "text",
	"std" => ""),
	
array(	"name" => "Performance",
	"desc" => "Select the type of performance you would like the slideshow to have",
	"id" => "performance",
	"options" => array('Normal', 'Hybrid speed/quality', 'Optimize image quality', 'Optimize transition speed (firefox/IE, not webkit)'),
	"type" => "select",
	"std" => ""),
	
array(	"name" => "Keyboard Navigation",
	"desc" => "Select whether or not you would like to be able to use the arrow keys to change images",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "keyboard_nav",
	"type" => "radio"),
	
array(	"name" => "Image Protection",
	"desc" => "Disable dragging images and right clicks using JavaScript",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "image_protect",
	"type" => "radio"),
	
array( "type" => "close"),
array( "name" => "Navigation Color Settings",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Logo Background Color",
	"desc" => "Choose the color you want for the background of your logo/site name.",
	"id" => "logo_bg_color",
	"type" => "color",
	"std" => "#000000"),
	
array( "name" => "Logo/Site Title Color",
	"desc" => "Select the color you would like to use for the site title.",
	"id" => "logo_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Navigation Link Background Color",
	"desc" => "Select the color you would like to use for the background of navigation links",
	"id" => "nav_link_bg_color",
	"type" => "color",
	"std" => "#000000"),
	
array( "name" => "Navigation Link Text Color",
	"desc" => "Select the color you would like to use for navigation links (1st level)",
	"id" => "nav_link_text_color",
	"type" => "color",
	"std" => "#ffffff"),

array( "name" => "Drop Down Menu Background Color",
	"desc" => "Select the color you would like to use for the background color of the drop down menu (2nd level)",
	"id" => "dd_bg_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Drop Down Menu Link Color",
	"desc" => "Select the color you would like to use for the site title.",
	"id" => "dd_link_color",
	"type" => "color",
	"std" => "#424242"),
	
array( "name" => "Drop Down Menu Link Hover Color",
	"desc" => "Select the color you would like to use for the drop down link hover.",
	"id" => "dd_link_hover_color",
	"type" => "color",
	"std" => "#000000"),
	
	
array( "type" => "close"),
array( "name" => "Page Color Settings",
	"type" => "section"),
array( "type" => "open"),
	
array( "name" => "Page Content Area Background Color",
	"desc" => "Select the background color you would like to use for the page content area",
	"id" => "page_content_bg_color",
	"type" => "color",
	"std" => "#000000"),
	
array( "name" => "Page Content Area Text Color",
	"desc" => "Select the color you would like to use for the page content area text",
	"id" => "page_content_text_color",
	"type" => "color",
	"std" => "#727272"),
	
array( "name" => "Page Content Area Text Link Color",
	"desc" => "Select the color you would like to use for the page content area textlink color.",
	"id" => "page_text_link_color",
	"type" => "color",
	"std" => "#ffffff"),

array( "name" => "Page Content Area Text Link HOVER Color",
	"desc" => "Select the color you would like to use for the page content area textlink hover color.",
	"id" => "page_text_link_hover_color",
	"type" => "color",
	"std" => "#999999"),
	
array( "name" => "Tag Cloud Background Color",
	"desc" => "Choose the color for the background of tag cloud links.",
	"id" => "widget_border_color",
	"type" => "color",
	"std" => "#212121"),
	
array( "name" => "Tag Cloud Link Color",
	"desc" => "Choose the color for tag cloud links",
	"id" => "tag_link_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Tag Cloud Link Hover Color",
	"desc" => "Choose the color for the tag cloud link hover",
	"id" => "tag_link_hover",
	"type" => "color",
	"std" => "#999999"),
	
array( "name" => "H1 Heading Color",
	"desc" => "",
	"id" => "h1_color",
	"type" => "color",
	"std" => "#ffffff"),
	
	array( "name" => "H2 Heading Color",
	"desc" => "",
	"id" => "h2_color",
	"type" => "color",
	"std" => "#ffffff"),
	
	array( "name" => "H3 Heading Color",
	"desc" => "",
	"id" => "h3_color",
	"type" => "color",
	"std" => "#ffffff"),
	
	array( "name" => "H4 Heading Color",
	"desc" => "",
	"id" => "h4_color",
	"type" => "color",
	"std" => "#ffffff"),
	
	array( "name" => "H5 Heading Color",
	"desc" => "",
	"id" => "h5_color",
	"type" => "color",
	"std" => "#ffffff"),
	
	array( "name" => "H6 Heading Color",
	"desc" => "",
	"id" => "h6_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Pagination Background Color",
	"desc" => "",
	"id" => "pagi_bg_color",
	"type" => "color",
	"std" => "#000000"),
	
array( "name" => "Pagination Current Color",
	"desc" => "",
	"id" => "pagi_current_color",
	"type" => "color",
	"std" => "#727272"),
	
array( "name" => "Pagination Link Color",
	"desc" => "",
	"id" => "pagi_link_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "type" => "close"),
array( "name" => "Sidebar Color Settings",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Sidebar Text Color",
	"desc" => "Select the color you would like to use for the sidebar text.",
	"id" => "sidebar_text_color",
	"type" => "color",
	"std" => "#727272"),
	
array( "name" => "Sidebar Link Color",
	"desc" => "Select the color you would like to use for the sidebar links.",
	"id" => "sidebar_link_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Sidebar Link Hover Color",
	"desc" => "Select the color you would like to use for the sidebar links when they're hovered on.",
	"id" => "sidebar_link_hover",
	"type" => "color",
	"std" => "#999999"),

array( "name" => "Sidebar List Border/Divider Color",
	"desc" => "Select the color you want to use for the sidebar list border color.",
	"id" => "sidebar_list_border_color",
	"type" => "color",
	"std" => "#212121"),
	
array( "type" => "close"),
array( "name" => "Blog Color Settings",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Blog Post Title (Link)",
	"desc" => "Select the color you would like to use for blog post titles (link).",
	"id" => "blog_title_color",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "name" => "Blog Post Title Link Hover",
	"desc" => "Select the color that you would like to show when the user hovers over the blog post title.",
	"id" => "blog_title_hover",
	"type" => "color",
	"std" => "#999999"),

array( "name" => "Blog Post Title Color (For Post Page)",
	"desc" => "Select the color you want the blog title to be on the main blog post page (not link)",
	"id" => "blog_title_page",
	"type" => "color",
	"std" => "#ffffff"),
	
array( "type" => "close"),
array( "name" => "Font Settings",
	"type" => "section"),
array( "type" => "open"),
	
array(	"name" => "Font Family",
	"desc" => "Select the font-family you would like to use.",
	"id" => "font_family",
	"options" => array('Arial, Helvetica, Garuda, sans-serif', 'Verdana, Geneva, Kalimati, sans-serif', 'Lucida Sans Unicode, Lucida Grande, Garuda, sans-serif', 'Georgia, Nimbus Roman No9 L, serif', 'Tahoma, Geneva, Kalimati, sans-serif', 'Trebuchet MS, Helvetica, Jamrul, sans-serif', 'Times New Roman, Times, FreeSerif, serif'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "Pagination Font",
	"desc" => "Enter the font that you want to use for the page navigation.",
	"id" => "pagi_font",
	"options" => array('Arial, Helvetica, Garuda, sans-serif', 'Verdana, Geneva, Kalimati, sans-serif', 'Lucida Sans Unicode, Lucida Grande, Garuda, sans-serif', 'Georgia, Nimbus Roman No9 L, serif', 'Tahoma, Geneva, Kalimati, sans-serif', 'Trebuchet MS, Helvetica, Jamrul, sans-serif', 'Times New Roman, Times, FreeSerif, serif'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "H1 Font Size",
	"desc" => "Font size for h1 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h1_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H2 Font Size",
	"desc" => "Font size for h2 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h2_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H3 Font Size",
	"desc" => "Font size for h3 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h3_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H4 Font Size",
	"desc" => "Font size for h4 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h4_size",
	"type" => "text",
	"std" => ""),

array( "name" => "H5 Font Size",
	"desc" => "Font size for h5 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h5_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H6 Font Size",
	"desc" => "Font size for h6 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h6_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Main Font Size",
	"desc" => "Font size for the main text in pixels only (enter the number of pixels only, nothing else)",
	"id" => "font_size",
	"type" => "text",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Single Portfolio Page",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Stacked/Slideshow",
	"desc" => "Select whether you would like the images for portfolio items to be stacked or put in a slideshow.",
	"desc2" => "Stacked",
	"desc3" => "Slideshow",
	"value" => "",
	"value2" => "1",
	"id" => "single_img_style",
	"type" => "radio"),

	
array( "type" => "close"),
array( "name" => "prettyPhoto (lightbox) Options",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Lightbox Theme",
	"desc" => "Enter the theme you would like to use for lightbox (prettyPhoto)",
	"id" => "lightbox_theme",
	"options" => array('Dark Rounded', 'Dark Square', 'Facebook', 'Light Rounded', 'Light Square'),
	"type" => "select",
	"std" => ""),
	
array(	"name" => "Show Title",
	"desc" => "Select whether or not you would like to display the lightbox title.",
	"desc2" => "Show Title",
	"desc3" => "Hide Title",
	"value" => "",
	"value2" => "1",
	"id" => "show_lb_title",
	"type" => "radio"),
	
array(	"name" => "Allow Resize",
	"desc" => "Select whether or not you would like to allow the user to view the full image size when lightbox is opened",
	"desc2" => "Allow",
	"desc3" => "Disallow",
	"value" => "",
	"value2" => "1",
	"id" => "allow_resize",
	"type" => "radio"),

array( "name" => "Opacity",
	"desc" => "Enter the opacity level you would like to use for the lightbox when opened (value between 0 and 1 - ex: 0.8)",
	"id" => "opacity",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Default Width",
	"desc" => "Enter the width (in pixels) you would like to use for default when prettyPhoto is opened (only if 'Allow Resize' is on)",
	"id" => "default_width",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Default Height",
	"desc" => "Enter the height (in pixels) you would like to use for default when prettyPhoto is opened (only if 'Allow Resize' is on)",
	"id" => "default_height",
	"type" => "text",
	"std" => ""),
	
	array( "type" => "close")
 
);
?>