<?php
/*
 * AP_TT_ : Tab Title
 * AP_TI_ : Tab Info
 * AP_ST_ : Section Title
 * AP_SI_ : Section Info
 * AP_OT_ : Option Title (label)
 * AP_OI_ : Option Info
 * AP_MT_ : Multi Option Title (label)
 * AP_MI_ : Multi Option Info
 * AP_OO_ : Option radio/checkbox/select label
 */
define( 'AP_TT_GENERAL', __( 'General', UT_THEME_NAME ) );
define( 'AP_TI_GENERAL', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_HEADER', __( 'Header', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_HEADER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOTYPE', __( 'Logo Type', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOTYPE', __( 'Text will show the blog title.', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_HEADER_LOGOTYPE_IMG', __( 'Image', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_HEADER_LOGOTYPE_TXT', __( 'Text', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOIMG', __( 'Logo Image', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOIMG', __( 'Upload and select your logo image. The headers height will adjust to the logo image height.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOTEXTSIZE', __( 'Text Logo Size', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOTEXTSIZE', __( 'Font size in px for text logo type.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_FAVICON', __( 'Favourite Icon', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_FAVICON', __( 'Set the favourite icon.', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_404', __( '404 Page No Found', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_404', __( 'The 404 page is shown, if the requested page does not exist.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_TITLE', __( 'Title', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_TITLE', __( 'Text on the left side below the header. Shortcodes available.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_TEASER', __( 'Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_TEASER', __( 'Text on the right side below the header. Shortcodes available.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_CONTENT', __( 'Content', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_CONTENT', __( 'The pages content. Shortcodes available.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_SIDEBAR', __( 'Sidebar', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_SIDEBAR', __( 'The pages sidebar. More sidebar can be added in tab "Sidebars".', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_SIDEBAR_ALIGN', __( 'Sidebar Align', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_SIDEBAR_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_404_SIDEBAR_ALIGN_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_404_SIDEBAR_ALIGN_RIGHT', __( 'Right', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_NOPOST', __( 'No Posts Found', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_NOPOST', __( 'This will be shown If a category, archive or search is requested, which has no post.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_TITLE', __( 'Title', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_TITLE', __( 'Text on the left side below the header. Shortcodes available.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_TEASER', __( 'Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_TEASER', __( 'Text on the right side below the header. Shortcodes available.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_CONTENT', __( 'Content', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_CONTENT', __( 'The pages content. Shortcodes available.', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_FOOTER', __( 'Footer', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_FOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_SIDEBAR', __( 'Sidebar', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_SIDEBAR', __( 'The footers sidebar. More sidebars can be added in tab "Sidebars".', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_LAYOUT', __( 'Layout', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_LAYOUT', __( 'The count and width of the sidebars widgets.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_COPYRIGHT', __( 'Copyright', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_COPYRIGHT', __( 'Some text at the very end of the site, usually copyright informations.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_GOOGLEANALYTICS', __( 'Google Analytics', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_GOOGLEANALYTICS', __( 'Enter the full Google analytics code.', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_CONTACTFORM', __( 'Contact Form', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_CONTACTFORM', __( 'Values for the contact form shortcode: [contactform]', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_NAME', __( 'Label Name', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_NAME', __( 'Text for the name label.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_MAIL', __( 'Label E-Mail', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_MAIL', __( 'Text for the e-mail label.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_MESSAGE', __( 'Label Message', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_MESSAGE', __( 'Text for the message label.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_SUBMIT', __( 'Submit Text', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_SUBMIT', __( 'Text for the submit button.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_NAME', __( 'Error Text Name', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_NAME', __( 'Failure text message for a less than 3 characters long name.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_MAIL', __( 'Error Text E-Mail', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_MAIL', __( 'Failure text message if the mail is not valid.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_MESSAGE', __( 'Error Text Message', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_MESSAGE', __( 'Failure text message for a less than 10 characters long message.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_TO', __( 'Default Mail Recipient', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_TO', __( 'The default e-mails recipient. Can be overwritten by shortcode attribute mailto="mail@address.com".', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_SUBJECT', __( 'Default Mail Subject', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_SUBJECT', __( 'The default e-mails subject. Can be overwritten by shortcode attribute subject="New Subject".', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_ERROR', __( 'Error Mail Text', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_ERROR', __( 'Text message for not send mail.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_SUCCESS', __( 'Success Mail Text', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_SUCCESS', __( 'Text message for successfull send mail.', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_COMMENTS', __( 'Comments Form', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_COMMENTS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSREQ', __( 'Required Fields', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSREQ', __( 'Text message for required fields in comments form.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSMAIL', __( 'E-Mail Publish', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSMAIL', __( 'Text message for not publishing e-mail address', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSTAGS', __( 'Allowed HTML', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSTAGS', __( 'Text message for allowed HTML tags', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTMOD', __( 'Moderation', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTMOD', __( 'Text message for comments, awaiting moderation.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_NAME', __( 'Error Text Name', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_NAME', __( 'Failure text message for a less than 3 characters long name.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_MAIL', __( 'Error Text E-Mail', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_MAIL', __( 'Failure text message if the mail is not valid.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_MESSAGE', __( 'Error Text Message', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_MESSAGE', __( 'Failure text message for a less than 10 characters long message.', UT_THEME_NAME ) );

define( 'AP_TT_STYLING', __( 'Styling', UT_THEME_NAME ) );
define( 'AP_TI_STYLING', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_BASIC', __( 'General', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_BASIC', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_BASIC_THEME_COLOR', __( 'Theme Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_BASIC_THEME_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_BASIC_THEME_FONT', __( 'Theme Font', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_BASIC_THEME_FONT', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_TOPBAR', __( 'Topbar', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_TOPBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_LINKCOLOR', __( 'Linkcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_LINKCOLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_LINKCOLOR_H', __( 'Linkcolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_LINKCOLOR_H', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_HEADER', __( 'Header', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_HEADER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_MENUCOLOR', __( 'Menucolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_MENUCOLOR', __( 'Link color for parent menu.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_SUBMENUCOLOR', __( 'Submenucolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_SUBMENUCOLOR', __( 'Link color for sub menu.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_MENUCOLOR_H', __( 'Menucolor hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_MENUCOLOR_H', __( 'Link color for menu on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_SUBMENUCOLOR_H', __( 'Submenucolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_SUBMENUCOLOR_H', __( 'Link color for sub menu on hover.', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_TEASER', __( 'Title & Teaser', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_TEASER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_TEXTCOLOR_TITLE', __( 'Color Title', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_TEXTCOLOR_TITLE', __( 'Text color for title (right).', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_TEXTCOLOR_TEASER', __( 'Color Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_TEXTCOLOR_TEASER', __( 'Text color for teaser (left).', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_LINKCOLOR', __( 'Linkcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_LINKCOLOR', __( 'Basic link color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_LINKCOLOR_H', __( 'Linkcolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_LINKCOLOR_H', __( 'Basic link color on hover.', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_SLIDER', __( 'Slider Caption', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_SLIDER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SLIDER_CAPTION_TEXT', __( 'Caption Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SLIDER_CAPTION_TEXT', __( 'Top caption text color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SLIDER_CAPTION_SHADOW', __( 'Caption Text Shadow', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SLIDER_CAPTION_SHADOW', __( 'Top caption text shadow color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SLIDER_SUBCAPTION_TEXT', __( 'Sub Caption Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SLIDER_SUBCAPTION_TEXT', __( 'Bottom caption text color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SLIDER_SUBCAPTION_SHADOW', __( 'Sub Caption Text Shadow', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SLIDER_SUBCAPTION_SHADOW', __( 'Bottom caption text shadow color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SLIDER_SUBCAPTION_BACKGROUND', __( 'Sub Caption Background', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SLIDER_SUBCAPTION_BACKGROUND', __( 'Bottom caption background color.', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_CONTENT', __( 'Content', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_CONTENT', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_TEXTCOLOR', __( 'Textcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_TEXTCOLOR', __( 'Basic text color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINKCOLOR', __( 'Linkcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINKCOLOR', __( 'Basic link color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINKCOLOR_H', __( 'Linkcolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINKCOLOR_H', __( 'Basic link color on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_PLINKCOLOR', __( 'Title Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_PLINKCOLOR', __( 'Text color for post and work titles.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_PLINKCOLOR_H', __( 'Title Color Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_PLINKCOLOR_H', __( 'Text color for post and work titles on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FLINKCOLOR', __( 'Fancy Link Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FLINKCOLOR', __( 'Link color for fancy link style.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FLINKCOLOR_H', __( 'Fancy Link Color Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FLINKCOLOR_H', __( 'Link color for fancy link style on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_BG', __( 'Field Background', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_BG', __( 'Background color for input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_TXT', __( 'Field Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_TXT', __( 'Text color for input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_BG_F', __( 'Field Background Focus', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_BG_F', __( 'Background color for focused input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_TXT_F', __( 'Field Text Focus', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_TXT_F', __( 'Text color for focused input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_BG', __( 'Button Background', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_BG', __( 'Background color for contact or search buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_TXT', __( 'Button Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_TXT', __( 'Text color for contact or search buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_BG_H', __( 'Button Background Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_BG_H', __( 'Background color for contact or search buttons on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_TXT_H', __( 'Button Text Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_TXT_H', __( 'Text color for contact or search buttons on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINE_COLOR_T', __( 'Line Top Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINE_COLOR_T', __( 'Color for the basic line. Set top and bottom color for this line.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINE_COLOR_B', __( 'Line Bottom Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINE_COLOR_B', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_FOOTER', __( 'Footer', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_FOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_TEXTCOLOR', __( 'Textcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_TEXTCOLOR', __( 'Basic text color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_LINKCOLOR', __( 'Linkcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_LINKCOLOR', __( 'Basic link color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_LINKCOLOR_H', __( 'Linkcolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_LINKCOLOR_H', __( 'Basic link color on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_BG', __( 'Field Background', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_BG', __( 'Background color for input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_TXT', __( 'Field Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_TXT', __( 'Text color for input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_BG_F', __( 'Field Background Focus', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_BG_F', __( 'Background color for focused input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_TXT_F', __( 'Field Text Focus', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_TXT_F', __( 'Text color for focused input fields and buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_BG', __( 'Button Background', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_BG', __( 'Background color for contact or search buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_TXT', __( 'Button Text', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_TXT', __( 'Text color for contact or search buttons.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_BG_H', __( 'Button Background Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_BG_H', __( 'Background color for contact or search buttons on hover.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_TXT_H', __( 'Button Text Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_TXT_H', __( 'Text color for contact or search buttons on hover.', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_SUBFOOTER', __( 'Bottombar', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_SUBFOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_COLOR', __( 'Background Color', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_IMAGE', __( 'Background Image', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_REPEAT', __( 'Image Repeat', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_REPEAT', __( 'How to repeat the image background.', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT', __( 'Repeat All', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT-X', __( 'Repeat X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT-Y', __( 'Repeat Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_NO-REPEAT', __( 'No Repeat', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_POSITION', __( 'Image Position', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_POSITION', __( 'The position sets the starting position of the background image. More infos on <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_TEXTCOLOR', __( 'Textcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_TEXTCOLOR', __( 'Basic text color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_LINKCOLOR', __( 'Linkcolor', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_LINKCOLOR', __( 'Basic link color.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_LINKCOLOR_H', __( 'Linkcolor Hover', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_LINKCOLOR_H', __( 'Basic link color on hover.', UT_THEME_NAME ) );

define( 'AP_TT_HOME', __( 'Home', UT_THEME_NAME ) );
define( 'AP_TI_HOME', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_WELCOME', __( 'Welcome Message', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_WELCOME', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_WELCOME_TEXT', __( 'Text', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_WELCOME_TEXT', __( 'Welcome message on start page below the slider. Shortcodes available.', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_FEATURED1', __( 'Service Columns', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_FEATURED1', __( 'Values for the three service columns on the startpage below the welcome message.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_FEATURED1_ITEM', __( 'Teaser Items', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_FEATURED1_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_HEAD', __( 'Title', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_HEAD', __( 'Title for the service column. Shortcodes available.', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_LINK', __( 'Link', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_LINK', __( 'Url which this item links to.', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_TEXT', __( 'Teaser', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_TEXT', __( 'Some teaser text which describes the item.', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_ICON', __( 'Icon', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_ICON', __( 'Upload and select an icon. The maximum size should be about 70px.', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_OVER', __( 'Hover', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_OVER', __( 'Link text for the hover event button, like "read more"', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_FEATURED2', __( 'Latest Articles', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_FEATURED2', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_FEATURED2_CATEGORY', __( 'Categories', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_FEATURED2_CATEGORY', __( 'Select at least one category to show the last three of them on the startpage below the service columns.', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_TWITTER', __( 'Twitter', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_TWITTER', __( 'Twitter setup to show tweets below the latest articles.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_USER', __( 'Username', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_USER', __( 'Set the username to show the tweets from.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_COUNT', __( 'Count', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_COUNT', __( 'How many tweets should be shown?', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_DEFAULT', __( 'Text default', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_DEFAULT', __( 'Auto text for non verb: "i said" bullocks.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_ED', __( 'Text past', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_ED', __( 'Auto text for past tense: "i" surfed', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_ING', __( 'Text present', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_ING', __( 'Auto tense for present tense: "i was" surfing', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_REPLY', __( 'Text reply', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_REPLY', __( 'Auto tense for replies: "i replied to" @someone "with"', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_URL', __( 'Text url', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_URL', __( 'Auto tense for urls: "i was looking at" http:...', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_LOADING', __( 'Text loading', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_LOADING', __( 'Optional loading text, displayed while tweets load', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_REFRESH', __( 'Reload Interval', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_REFRESH', __( 'Optional number of seconds after which to reload tweets. "Null" does not reload tweets.', UT_THEME_NAME ) );

define( 'AP_TT_SLIDER', __( 'Slider', UT_THEME_NAME ) );
define( 'AP_TI_SLIDER', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SLIDER_OPTIONS', __( 'Options', UT_THEME_NAME ) );
	define( 'AP_SI_SLIDER_OPTIONS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_HEIGHT', __( 'Height', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_HEIGHT', __( 'Height of the slider. Images should be at least the same height.', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_EFFECT', __( 'Effect', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_EFFECT', __( 'Select the animation effect.', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_EFFECT_SLIDE', __( 'Slide', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_EFFECT_FADE', __( 'Fade', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_AUTOPLAY', __( 'Autoplay', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_AUTOPLAY', __( 'Select if the slideshow will start running.', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_AUTOPLAY_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_AUTOPLAY_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_DELAY', __( 'Delay', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_DELAY', __( 'How long between slideshow transitions in AutoPlay mode (in milliseconds).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_RESUMEDELAY', __( 'Resume Delay', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_RESUMEDELAY', __( 'Resume slideshow after user interaction, only if autoplayLocked is true (in milliseconds).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_ANIMATIONTIME', __( 'Animation Time', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_ANIMATIONTIME', __( 'How long the slideshow transition takes (in milliseconds).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_DELAYBEFOREANIMATE', __( 'Delay Before Animation', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_DELAYBEFOREANIMATE', __( 'How long to pause slide animation before going to the desired slide.', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_HOVERPAUSE', __( 'Pause On Hover', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_HOVERPAUSE', __( 'Select if the slideshow will pause on mouse hover.', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_HOVERPAUSE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_HOVERPAUSE_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_STOPEND', __( 'Stop End', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_STOPEND', __( 'This will stop the slideshow on the last page if autoplay is active.', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_STOPEND_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_STOPEND_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_NAVI', __( 'Display Navi', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_NAVI', __( 'How to display the slider navigation.', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_NAVI_NONE', __( 'Hide', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_NAVI_NAVI', __( 'Numbers', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_NAVI_THUMBS', __( 'Numbers & Thumbs', UT_THEME_NAME ) );
	define( 'AP_ST_SLIDER_ITEMS', __( 'Manage Items', UT_THEME_NAME ) );
	define( 'AP_SI_SLIDER_ITEMS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_ITEMS_ITEM', __( 'Slider Items', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CUSTOM', __( 'Custom Content', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CUSTOM', __( 'Embedd custom content, e.g. video, with shortcode or regular HTML. Leave blank to display the image.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_IMAGE', __( 'Image', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_IMAGE', __( 'Upload and select an image.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_THUMB', __( 'Thumbnail', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_THUMB', __( 'Upload and select the images thumbnail. Dimensions should be 80x80px.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_LINKURL', __( 'Image Link', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_LINKURL', __( 'Link slider image to an url. Has no effect on custom content. Leave blank for no link.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_TITLE', __( 'Caption Title', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_TITLE', __( 'Fist line caption text.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_SUBTITLE', __( 'Caption Subtitle', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_SUBTITLE', __( 'Second line caption text.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_POS', __( 'Caption Position', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_POS', __( 'Select the side where the caption appears.', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_TOP', __( 'Top', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_RIGHT', __( 'Right', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_BOTTOM', __( 'Bottom', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_DIS', __( 'Caption Distance', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_DIS', __( 'Distance in px the caption will slide to from position.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_DUR', __( 'Caption Duration', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_DUR', __( 'Time how long the caption slides in (in milliseconds).', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_EASING', __( 'Caption Easing', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_EASING', __( 'Animation type for the caption slide in effect.', UT_THEME_NAME ) );

define( 'AP_TT_BLOG', __( 'Blog', UT_THEME_NAME ) );
define( 'AP_TI_BLOG', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_TITLETEASER', __( 'Title & Teaser', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_TITLETEASER', __( 'The default text for titles & teasers. Shortcodes are available.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_POST_TITLE', __( 'Post Title', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_POST_TITLE', __( 'Default title for single posts. Can be overwritten by its categories and the post itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_POST_TEASER', __( 'Post Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_POST_TEASER', __( 'Default teaser for single posts. Can be overwritten by its categories and the post itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_CATEGORY_TITLE', __( 'Category Title', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_CATEGORY_TITLE', __( 'Default title for category listings. Can be overwritten by category itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_CATEGORY_TEASER', __( 'Category Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_CATEGORY_TEASER', __( 'Default teaser for category listings. Can be overwritten by category itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_ARCHIVE_TITLE', __( 'Archive Title', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_ARCHIVE_TITLE', __( 'Title for archive listings.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_ARCHIVE_TEASER', __( 'Archive Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_ARCHIVE_TEASER', __( 'Teaser for archive listings.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_SEARCH_TITLE', __( 'Search Results Title', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_SEARCH_TITLE', __( 'Title for search results.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_SEARCH_TEASER', __( 'Search Results Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_SEARCH_TEASER', __( 'Teaser for search results.', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_SIDEBAR', __( 'Default Sidebar Options', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_SIDEBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_POST', __( 'Posts', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_POST', __( 'Default sidebar for single posts. Can be overwritten by its categories and the post itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_POST_ALIGN', __( 'Align', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_POST_ALIGN', __( 'Default sidebar align for single posts.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_POST_ALIGN_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_POST_ALIGN_RIGHT', __( 'Right', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_CATEGORY', __( 'Categories', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_CATEGORY', __( 'Default sidebar for category listings. Can be overwritten by category itself.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_CATEGORY_ALIGN', __( 'Align', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_CATEGORY_ALIGN', __( 'Default sidebar align for category listings.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_CATEGORY_ALIGN_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_CATEGORY_ALIGN_RIGHT', __( 'Right', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_ARCHIVE', __( 'Archives', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_ARCHIVE', __( 'Sidebar for archive listings.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_ARCHIVE_ALIGN', __( 'Align', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_ARCHIVE_ALIGN', __( 'Sidebar align for archive listings.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_ARCHIVE_ALIGN_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_ARCHIVE_ALIGN_RIGHT', __( 'Right', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_SEARCH', __( 'Search Result', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_SEARCH', __( 'Sidebar forsearch results.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_SEARCH_ALIGN', __( 'Align', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_SEARCH_ALIGN', __( 'Sidebar align forsearch results.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_SEARCH_ALIGN_LEFT', __( 'left', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_SEARCH_ALIGN_RIGHT', __( 'right', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_LISTING', __( 'Post Listing', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_LISTING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_LENGTH', __( 'Length', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_LENGTH', __( 'Number of words to show.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_READMORE', __( 'More Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_READMORE', __( 'Link text for hover button, like "read more".', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_NEXTLINK', __( 'Navi Next Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_NEXTLINK', __( 'Link text for next site, like "older posts".', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_PREVLINK', __( 'Navi Previous Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_PREVLINK', __( 'Link text for previous site, like "newer posts".', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_THUMB', __( 'Thumbnail Heights', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_THUMB', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_HEIGHT_WSB', __( 'Thumbnail Height Normal', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_HEIGHT_WSB', __( 'Thumbnail height for featured images on site with sidebar.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_HEIGHT_NSB', __( 'Thumbnail Height Full Width', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_HEIGHT_NSB', __( 'Thumbnail height for featured images on site without sidebar.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_CROP', __( 'Crop Image', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_CROP', __( 'Select "No" to set the thumbnail size by resizing the image proportionally without distorting it or "Yes" by cropping the image (either from the sides, or from the top and bottom).', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_THUMB_CROP_Y', __( 'yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_THUMB_CROP_N', __( 'No', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_READING', __( 'Reading', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_DISABLE_AUTOP', __( 'Disable Wp Auto p-Tags', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_DISABLE_AUTOP', __( 'Wordpress adds automaticly &lt;p&gt; tags in content. This can disturb the layout when using shortcodes. Disable and use shortcode [p][/p] or [br] instead.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_DISABLE_AUTOP_NO', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_PASSPOST', __( 'Password Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_PASSPOST', __( 'Text message for password protected posts.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_COMMENTSHIDE', __( 'Hide Closed Comments', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_COMMENTSHIDE', __( 'Select "Yes" to hide the whole comment block if comments are disabled for this post.', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_TXT_COMMENTSHIDE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_TXT_COMMENTSHIDE_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_COMMENTSCLOSED', __( 'Comments Closed Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_COMMENTSCLOSED', __( 'Text message for closed comments.', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_PASSCOMM', __( 'Comments Password Text', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_PASSCOMM', __( 'Comments message for password protected posts.', UT_THEME_NAME ) );

define( 'AP_TT_PAGES', __( 'Pages', UT_THEME_NAME ) );
define( 'AP_TI_PAGES', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_TITLETEASER', __( 'Teaser', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_TITLETEASER', __( 'The default text for teasers. Shortcodes are available.', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_TITLETEASER_TEASER', __( 'Page Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_TITLETEASER_TEASER', __( 'Default teaser for pages. Can be overwritten by the page itself.', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_SIDEBAR', __( 'Default Sidebar Options', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_SIDEBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_SIDEBAR_SIDEBAR', __( 'Sidebar', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_SIDEBAR_SIDEBAR', __( 'Default sidebar for pages. Can be overwritten by the page itself.', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_SIDEBAR_ALIGN', __( 'Page Sidebar Align', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_SIDEBAR_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_SIDEBAR_ALIGN_LEFT', __( 'Left', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_SIDEBAR_ALIGN_RIGHT', __( 'Right', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_READING', __( 'Reading', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_DISABLE_AUTOP', __( 'Disable Wp Auto p-Tags', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_DISABLE_AUTOP', __( 'Wordpress adds automaticly &lt;p&gt; tags in content. This can disturb the layout when using shortcodes. Disable and use shortcode [p][/p] or [br] instead.', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_DISABLE_AUTOP_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_COMMENTSHIDE', __( 'Hide Closed Comments', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_COMMENTSHIDE', __( 'Select "Yes" to hide the whole comment block if comments are disabled for this page.', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_TXT_COMMENTSHIDE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_TXT_COMMENTSHIDE_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_COMMENTSCLOSED', __( 'Comments Closed Text', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_COMMENTSCLOSED', __( 'Text message for closed comments.', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_PASSPOST', __( 'Password Text', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_PASSPOST', __( 'Text message for password protected pages.', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_PASSCOMM', __( 'Comments Password Text', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_PASSCOMM', __( 'Comments message for password protected pages.', UT_THEME_NAME ) );

define( 'AP_TT_PORTFOLIO', __( 'Portfolio', UT_THEME_NAME ) );
define( 'AP_TI_PORTFOLIO', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_GENERAL', __( 'General', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_GENERAL', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_LAYOUT', __( 'Default Layout', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_LAYOUT', __( 'Select the default work listing. Can be overwitten by each category.', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_FILT', __( 'Filter', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_1COL', __( '1 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_2COL', __( '2 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_3COL', __( '3 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_4COL', __( '4 Column', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_READMORE', __( 'More Text', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_READMORE', __( 'Text for on hover link, like "see more"', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_LINKTEXT', __( 'Link Text', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_LINKTEXT', __( 'Text for project link in works, like "visit project"', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_TITLETEASER', __( 'Title & Teaser', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_TITLETEASER', __( 'The default text for titles & teasers. Shortcodes are available.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_WORK_TITLE', __( 'Work Title', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_WORK_TITLE', __( 'Default title for portolio works. Can be overwritten by the work itself.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_WORK_TEASER', __( 'Work Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_WORK_TEASER', __( 'Default teaser for portolio works. Can be overwritten by the work itself.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_CATEGORY_TITLE', __( 'Category Title', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_CATEGORY_TITLE', __( 'Default title for portolio categories. Can be overwritten by each category itself.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_CATEGORY_TEASER', __( 'Category Teaser', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_CATEGORY_TEASER', __( 'Default teaser for portolio categories. Can be overwritten by each category itself.', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_THUMB', __( 'Thumbnails', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_THUMB', __( 'Set the thumbnails height for each layout. Crop: Select "No" to set the thumbnail size by resizing the image proportionally without distorting it or "Yes" by cropping the image (either from the sides, or from the top and bottom).', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_FILT', __( 'Filter Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_FILT', __( 'Thumbnail height in px for filter layout. Width fixed to: 318px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_FILT', __( 'Filter Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_FILT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_FILT_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_FILT_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_1COL', __( '1 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_1COL', __( 'Thumbnail height in px for 1 column layout. Width fixed to: 626px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_1COL', __( '1 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_1COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_1COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_1COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_2COL', __( '2 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_2COL', __( 'Thumbnail height in px for 2 column layout. Width fixed to: 462px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_2COL', __( '2 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_2COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_2COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_2COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_3COL', __( '3 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_3COL', __( 'Thumbnail height in px for 3 column layout. Width fixed to: 298px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_3COL', __( '3 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_3COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_3COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_3COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_4COL', __( '4 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_4COL', __( 'Thumbnail height in px for 4 column layout. Width fixed to: 216px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_4COL', __( '4 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_4COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_4COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_4COL_N', __( 'No', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_LISTING', __( 'Listing', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_LISTING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_FILT', __( 'Count Filter', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_FILT', __( 'How many works to show on filter layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_1COL', __( 'Count 1 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_1COL', __( 'How many works to show on 1 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_1COL', __( 'Length 1 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_1COL', __( 'How many words to show on 1 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_2COL', __( 'Count 2 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_2COL', __( 'How many works to show on 2 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_2COL', __( 'Length 2 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_2COL', __( 'How many words to show on 2 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_3COL', __( 'Count 3 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_3COL', __( 'How many works to show on 3 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_3COL', __( 'Length 3 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_3COL', __( 'How many words to show on 3 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_4COL', __( 'Count 4 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_4COL', __( 'How many works to show on 4 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_4COL', __( 'Length 4 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_4COL', __( 'How many words to show on 4 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_NEXTTEXT', __( 'Next Text', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_NEXTTEXT', __( 'Text for "next works" link.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_PREVTEXT', __( 'Previous Text', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_PREVTEXT', __( 'Text for "previous works" link.', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_READING', __( 'Reading', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_READING_DISABLE_AUTOP', __( 'Disable Wp Auto p-Tags', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_READING_DISABLE_AUTOP', __( 'Wordpress adds automaticly &lt;p&gt; tags in content. This can disturb the layout when using shortcodes. Disable and use shortcode [p][/p] or [br] instead.', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_READING_DISABLE_AUTOP_NO', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_READING_TXT_PASSPOST', __( 'Password Text', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_READING_TXT_PASSPOST', __( 'Text message for password protected works.', UT_THEME_NAME ) );

define( 'AP_TT_SOCIAL', __( 'Social', UT_THEME_NAME ) );
define( 'AP_TI_SOCIAL', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SOCIAL_OPTIONS', __( 'Social Links Options', UT_THEME_NAME ) );
	define( 'AP_SI_SOCIAL_OPTIONS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_HEADER', __( 'Header', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_HEADER', __( 'Show social links at the very beginning of the site, above the header.', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_HEADER_Y', __( 'yes', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_HEADER_N', __( 'no', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_FOOTER', __( 'Footer', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_FOOTER', __( 'Show social links at the very beginning of the site, below the footer.', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_FOOTER_Y', __( 'yes', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_FOOTER_N', __( 'no', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_OPEN', __( 'Open Links in', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_OPEN', __( 'How to open the social links.', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_OPEN_SAME', __( 'same Window', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_OPEN_NEW', __( 'new Window', UT_THEME_NAME ) );
	define( 'AP_ST_SOCIAL_LINKS', __( 'Edit Social Links', UT_THEME_NAME ) );
	define( 'AP_SI_SOCIAL_LINKS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_LINKS_LINK', __( 'Soacial Links', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_LINKS_LINK', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SOCIAL_LINKS_LINK_NAME', __( 'Name', UT_THEME_NAME ) );
			define( 'AP_MI_SOCIAL_LINKS_LINK_NAME', __( 'This is the name and the text for the social link.', UT_THEME_NAME ) );
			define( 'AP_MT_SOCIAL_LINKS_LINK_LINK', __( 'Link', UT_THEME_NAME ) );
			define( 'AP_MI_SOCIAL_LINKS_LINK_LINK', __( 'This is the url of the social link.', UT_THEME_NAME ) );

define( 'AP_TT_FONTS', __( 'Fonts', UT_THEME_NAME ) );
define( 'AP_TI_FONTS', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_FONTS_MANAGE', __( 'Manage Fonts', UT_THEME_NAME ) );
	define( 'AP_SI_FONTS_MANAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_FONTS_MANAGE_FONT', __( 'Fonts', UT_THEME_NAME ) );
		define( 'AP_OI_FONTS_MANAGE_FONT', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_NAME', __( 'Name', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_NAME', __( 'The name of the font family, as set in the css.', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_URL', __( 'Url', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_URL', __( 'The stylesheet url.', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_ALT', __( 'Alternative', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_ALT', __( 'Comma seperated alternative fonts, like "serif", "sans-serif" or "Verdana"', UT_THEME_NAME ) );

define( 'AP_TT_SIDEBARS', __( 'Sidebars', UT_THEME_NAME ) );
define( 'AP_TI_SIDEBARS', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SIDEBARS_MANAGE', __( 'Manage Sidebars', UT_THEME_NAME ) );
	define( 'AP_SI_SIDEBARS_MANAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SIDEBARS_MANAGE_SIDEBAR', __( 'Sidebars', UT_THEME_NAME ) );
		define( 'AP_OI_SIDEBARS_MANAGE_SIDEBAR', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SIDEBARS_MANAGE_SIDEBAR_NAME', __( 'Sidebar Title', UT_THEME_NAME ) );
			define( 'AP_MI_SIDEBARS_MANAGE_SIDEBAR_NAME', __( 'Give the sidebar a name.', UT_THEME_NAME ) );
			define( 'AP_MT_SIDEBARS_MANAGE_SIDEBAR_DESCRIPTION', __( 'Sidebar Description', UT_THEME_NAME ) );
			define( 'AP_MI_SIDEBARS_MANAGE_SIDEBAR_DESCRIPTION', __( 'Optional sidbar desciption.', UT_THEME_NAME ) );

define( 'AP_TT_BOXES', __( 'Custom Boxes', UT_THEME_NAME ) );
define( 'AP_TI_BOXES', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_BOXES_ITEMS', __( 'Custom Boxes', UT_THEME_NAME ) );
	define( 'AP_SI_BOXES_ITEMS', __( 'Add custom boxes for shortcode', UT_THEME_NAME ) );
		define( 'AP_OT_BOXES_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
		define( 'AP_OI_BOXES_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_NAME', __( 'Name', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_NAME', __( 'The style name for use like<br />[box style="the_name"]', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_ICON', __( 'Icon', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_ICON', __( 'Upload and select item. The Size should be 32x32px.', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-BG', __( 'Background Color', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-BG', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-BD', __( 'Border Color', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-BD', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-TX', __( 'Text Color', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-TX', __( '', UT_THEME_NAME ) );
?>