<?php
/*
  $Id: conditions.php 1739 2007-12-20 00:52:16Z hpdl $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2002 osCommerce

  Released under the GNU General Public License
*/

define('NAVBAR_TITLE', 'Conditions of Use');
define('HEADING_TITLE', 'Conditions of Use');

define('TEXT_INFORMATION', '<br /><p>Welcome to our online  store! New Life Office and its associates provide their services to you subject to the following conditions. If you visit or shop within this website, you accept these conditions. Please read them carefully.<br />
    <br /><strong>PRIVACY</strong><br /><br />
  Please review our Privacy Notice, which also governs your visit to our website, to understand our practices.<br /><br />
  <strong>ELECTRONIC COMMUNICATIONS</strong><br /><br />
  When you visit New Life Office or send e-mails to us, you are communicating with us electronically. You consent to receive communications from  us electronically. We will communicate with you by e-mail or by posting notices  on this site. You agree that all agreements, notices, disclosures and other  communications that we provide to you electronically satisfy any legal  requirement that such communications be in writing.<br /><br />
  <strong>COPYRIGHT</strong><br /><br />
  All content included on this site, such as text, graphics,  logos, button icons, images, audio clips, digital downloads, data compilations,  and software, is the property of New Life Office or its content suppliers and  protected by United States and international copyright laws. The compilation of  all content on this site is the exclusive property of New Life Office, with  copyright authorship for this collection by&nbsp;<a href="http://www.goddardhewett.com/">Goddard  Hewett</a>, and protected by  U.S. and international copyright laws. The software application provider and  author for &quot;osCommerce&quot;, is used under the GNU GENERAL PUBLIC LICENSE  and all original authorship and credit for osCommerce remains the intellectual  rights of www.oscommerce.com.<br /><br />
  <strong>TRADEMARKS</strong><br /><br />
  New Life Office trademarks and trade dress may not be used in  connection with any product or service that is not New Life Office\'s, in any  manner that is likely to cause confusion among customers, or in any manner that  disparages or discredits New Life Office. All other trademarks not owned by New  Life Office or its subsidiaries that appear on this site are the property of  their respective owners, who may or may not be affiliated with, connected to,  or sponsored by New Life Office or its subsidiaries.<br /><br />
  <strong>LICENSE AND SITE ACCESS</strong><br /><br />
  New Life Office grants you a limited license to access and make  personal use of this site and not to download (other than page caching) or  modify it, or any portion of it, except with express written consent of New  Life Office. This license does not include any resale or commercial use of this  site or its contents: any collection and use of any product listings,  descriptions, or prices: any derivative use of this site or its contents: any  downloading or copying of account information for the benefit of another  merchant: or any use of data mining, robots, or similar data gathering and  extraction tools. This site or any portion of this site may not be reproduced,  duplicated, copied, sold, resold, visited, or otherwise exploited for any  commercial purpose without express written consent of New Life Office. You may  not frame or utilize framing techniques to enclose any trademark, logo, or  other proprietary information (including images, text, page layout, or form)  of  New Life Office and our associates  without express written consent. You may not use any meta tags or any other  &quot;:hidden text&quot;: utilizing New Life Office\'s name or trademarks  without the express written consent of New Life Office. Any unauthorized use  terminates the permission or license granted by New Life Office. You are  granted a limited, revocable, and nonexclusive right to create a hyperlink to  the home page of New Life Office so long as the link does not portray New Life  Office, its associates, or their products or services in a false, misleading,  derogatory, or otherwise offensive matter. You may not use any New Life Office  logo or other proprietary graphic or trademark as part of the link without  express written permission.<br /><br />
  <strong>YOUR MEMBERSHIP ACCOUNT</strong><br /><br />
  If you use this site, you are responsible for maintaining the  confidentiality of your account and password and for restricting access to your  computer, and you agree to accept responsibility for all activities that occur  under your account or password. If you are under 18, you may use our website  only with involvement of a parent or guardian. New Life Office and its  associates reserve the right to refuse service, terminate accounts, remove or  edit content, or cancel orders in their sole discretion.<br /><br />
  <strong>REVIEWS, COMMENTS, EMAILS, AND OTHER CONTENT</strong><br /><br />
  Visitors may post reviews, comments, and other content: and  submit suggestions, ideas, comments, questions, or other information, so long  as the content is not illegal, obscene, threatening, defamatory, invasive of  privacy, infringing of intellectual property rights, or otherwise injurious to  third parties or objectionable and does not consist of or contain software  viruses, political campaigning, commercial solicitation, chain letters, mass  mailings, or any form of &quot;:spam.&quot;: You may not use a false e-mail  address, impersonate any person or entity, or otherwise mislead as to the  origin of a card or other content. New Life Office reserves the right (but not  the obligation) to remove or edit such content, but does not regularly review  posted content.<br /><br />
  If you do post content or submit material, and unless we  indicate otherwise, you grant New Life Office and its associates a  nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable  right to use, reproduce, modify, adapt, publish, translate, create derivative  works from, distribute, and display such content throughout the world in any  media. You grant New Life Office and its associates and sublicensees the right  to use the name that you submit in connection with such content, if they  choose. You represent and warrant that you own or otherwise control all of the  rights to the content that you post: that the content is accurate: that use of  the content you supply does not violate this policy and will not cause injury  to any person or entity: and that you will indemnify New Life Office or its  associates for all claims resulting from content you supply. New Life Office  has the right but not the obligation to monitor and edit or remove any activity  or content. New Life Office takes no responsibility and assumes no liability  for any content posted by you or any third party.<br /><br />
  <strong>RISK OF LOSS</strong><br /><br />
  All items purchased from New Life Office are made pursuant to a  shipment contract. This basically means that the risk of loss and title for  such items pass to you upon our delivery to the carrier.<br /><br />
  <strong>PRODUCT DESCRIPTIONS</strong><br /><br />
  New Life Office and its associates attempt to be as accurate as  possible. However, New Life Office does not warrant that product descriptions  or other content of this site is accurate, complete, reliable, current, or  error-free. If a product offered by New Life Office itself is not as described,  your sole remedy is to return it in unused condition.<br /><br />
  DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY<br /><br />
  THIS SITE IS PROVIDED BY New Life Office ON AN &quot;:AS  IS&quot;: AND &quot;:AS AVAILABLE&quot;: BASIS. New Life Office MAKES NO  REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE  OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS  INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT  YOUR SOLE RISK.<br /><br />
  TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, New Life  Office DISCLAIMS ALL WARRANTIES, EXPRESS OR  IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS FOR A PARTICULAR PURPOSE. New Life Office DOES NOT WARRANT THAT  THIS SITE, ITS SERVERS, OR E-MAIL SENT FROM New Life Office ARE FREE OF VIRUSES  OR OTHER HARMFUL COMPONENTS. New Life Office WILL NOT BE LIABLE FOR ANY DAMAGES  OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO  DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES.<br /><br />
  CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED  WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS  APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS  MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.<br /><br />
  <strong>APPLICABLE LAW</strong><br /><br />
  By visiting New Life Office, you agree that the laws of the  state of Utah, without regard to principles of conflict of laws, will govern  these Conditions of Use and any dispute of any sort that might arise between  you and New Life Office or its associates.<br /><br />
  <strong>DISPUTES</strong><br /><br />
  Any dispute relating in any way to your visit to New Life Office  or to products you purchase through New Life Office shall be submitted to  confidential arbitration in Utah, except that, to the extent you have in any  manner violated or threatened to violate New Life Office\'s intellectual  property rights, New Life Office may seek injunctive or other appropriate  relief in any state or federal court in the state of Utah, and you consent to  exclusive jurisdiction and venue in such courts. Arbitration under this  agreement shall be conducted under the rules then prevailing of the American  Arbitration Association. The arbitrators award shall be binding and may be  entered as a judgment in any court of competent jurisdiction. To the fullest  extent permitted by applicable law, no arbitration under this Agreement shall  be joined to an arbitration involving any other party subject to this  Agreement, whether through class arbitration proceedings or otherwise.<br /><br />
  <strong>SITE POLICIES, MODIFICATION, AND SEVERABILITY</strong><br /><br />
  Please review our other policies, such as our Shipping and  Returns policy, posted on this site. These policies also govern your visit to  New Life Office. We reserve the right to make changes to our site, policies,  and these Conditions of Use at any time. If any of these conditions shall be  deemed invalid, void, or for any reason unenforceable, that condition shall be  deemed severable and shall not affect the validity and enforceability of any  remaining condition.<br /><br />
  <strong>QUESTIONS:</strong><br /><br />
  Questions regarding our Conditions of Usage, Privacy Policy, or  other policy related material can be directed to our support staff by using  our&nbsp;<a href="https://ssl37.pair.com/inksp3c1/ldsgreats/contact_us.php">Contact Us</a>&nbsp;page. Or you can email us at: <a href="mailto:info@newlifeoffice.com"><u>info@newlifeoffice.com</u></a></p>');
?>